import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='mt-64 w-full h-full flex flex-col items-center justify-center gap-5'>
        <h1 className='font-bold text-4xl'>Profile Builder</h1>
        <button className='bg-violet-900 hover:bg-violet-500 rounded-xl text-white p-5' onClick={() => {
          window.location.href = '/login'
        }}>Login</button>
      </div>
    </div>
  )
}
