import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='w-full h-full flex items-center justify-center'>
        <div>Profile Builder</div>
        <button onClick={() => {
          window.location.href = '/login'
        }}>Login</button>
      </div>
    </div>
  )
}
